options:
  logging: CLOUD_LOGGING_ONLY

env:
- 'LOCATION=$LOCATION'
# - 'PROJECT_ID=advanced-sof'
- 'TAG_NAME=$TAG_NAME'
- 'REPO_NAME=$REPO_NAME'

steps:
- name: 'ubuntu'
  script: |
    #!/usr/bin/env bash
    echo "$LOCATION advanced-sof $TAG_NAME $REPO_NAME"

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/advanced-sof/$REPO_NAME/5667-game$TAG_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$LOCATION-docker.pkg.dev/advanced-sof/$REPO_NAME/5667-game$TAG_NAME']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'the-game', '--image', '$LOCATION-docker.pkg.dev/advanced-sof/$REPO_NAME/5667-game$TAG_NAME', '--region', '$LOCATION']
images:
- '$LOCATION-docker.pkg.dev/advanced-sof/$REPO_NAME/5667-game:$TAG_NAME'


