options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/5667-game$TAG_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/5667-game$TAG_NAME']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'the-game', '--image', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/5667-game$TAG_NAME', '--region', '$LOCATION']
images:
- '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/5667-game:$TAG_NAME'


