options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/advanced-sof/cs-5667-game/5667-game', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/advanced-sof/cs-5667-game/5667-game']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'the-game', '--image', 'us-central1-docker.pkg.dev/advanced-sof/cs-5667-game/5667-game', '--region', 'us-central1']

images:
- 'us-central1-docker.pkg.dev/advanced-sof/cs-5667-game/5667-game'


